# Generated by Django 4.2.6 on 2023-11-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartSummary',
        ),
    ]
