# Generated by Django 4.2.6 on 2023-11-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
